FROM ghcr.io/media-apps/base:debian13

# URL of the ownCloud server bundle to unpack into /var/www.
# CI must set this via build-args; we keep a sane default for local builds.
ARG TARBALL_URL="https://download.owncloud.com/server/stable/owncloud-10.16.1.tar.bz2"

LABEL maintainer="ownCloud GmbH " \
 org.opencontainers.image.authors="ownCloud DevOps " \
 org.opencontainers.image.vendor="ownCloud GmbH" \
 org.opencontainers.image.title="ownCloud Server" \
 org.opencontainers.image.description="ownCloud - Secure Collaboration Platform" \
 org.opencontainers.image.url="https://hub.docker.com/r/owncloud/server" \
 org.opencontainers.image.source="https://github.com/owncloud-docker/server" \
 org.opencontainers.image.documentation="https://github.com/owncloud-docker/server"

ADD --unpack "${TARBALL_URL}" /var/www/
RUN ls -l /var/www && ls -l /var/www/owncloud

ADD overlay /
WORKDIR /var/www/owncloud

USER root
RUN find /var/www/owncloud \( \! -user www-data -o \! -group root \) -print0 | xargs -r -0 chown www-data:root && \
  chmod g+w /var/www/owncloud && \
  if [ -f /var/www/owncloud/.htaccess ]; then chmod g+w /var/www/owncloud/.htaccess; fi
USER www-data

VOLUME ["/mnt/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/owncloud", "server"]
